/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;

import org.example.v1_0.imperative.AllImperative;
import org.example.v1_0.imperative.LeetCode;

public class App {

    public static void main(String[] args) {
        AllImperative.run();
        int[] example1 = { 2, 7, 11, 15 };
        int[] example2 = { 3, 2, 4 };
        int[] example3 = { 432, 4325, 223, 1 };

        System.out.println(Arrays.toString(LeetCode.twoSum(example1, 9)));
        System.out.println(Arrays.toString(LeetCode.twoSum(example2, 6)));
        System.out.println(Arrays.toString(LeetCode.twoSum(example3, 9)));
    }
}
